# Generated by Django 4.2.10 on 2025-03-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("premissas", "0004_alter_criterios_tipo_conversao"),
        ("avaliacao", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_atualizaca_logs_correto",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_category_correto",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_cliente_notificado",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_contrato_lancado",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_descricao_troubleshooting",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_has_met_first_response_target",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_horas_lancadas",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_resolution_target",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="is_ticket_encerrado_corretamente",
        ),
        migrations.CreateModel(
            name="ResultadoAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.FloatField(help_text="Nota atribuída ao critério")),
                (
                    "data_referencia",
                    models.DateTimeField(
                        help_text="Data de referência para a avaliação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de criação"
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        help_text="FK da Avaliação",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultado_avaliacao",
                        to="avaliacao.avaliacao",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        help_text="Critério avaliado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultado_avaliacao",
                        to="premissas.criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota da Avaliação",
                "verbose_name_plural": "Notas das Avaliações",
                "db_table": "f_nota_avaliacao",
                "unique_together": {("avaliacao", "criterio")},
            },
        ),
        migrations.CreateModel(
            name="NotaCriterioConversao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="avaliacao.avaliacao",
                    ),
                ),
                (
                    "conversao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas",
                        to="premissas.conversao",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="premissas.criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Critério Conversão",
                "verbose_name_plural": "Notas Critérios Conversão",
                "db_table": "avaliacao_nota_criterio_conversao",
                "abstract": False,
                "unique_together": {("avaliacao", "criterio")},
            },
        ),
        migrations.CreateModel(
            name="NotaCriterioBooleano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valor", models.BooleanField(help_text="Valor booleano (True/False)")),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="avaliacao.avaliacao",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="premissas.criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Critério Booleano",
                "verbose_name_plural": "Notas Critérios Booleanos",
                "db_table": "avaliacao_nota_criterio_booleano",
                "abstract": False,
                "unique_together": {("avaliacao", "criterio")},
            },
        ),
    ]
