# Generated by Django 4.2.10 on 2025-03-10 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacao", "0002_remove_avaliacao_is_atualizaca_logs_correto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resultadoavaliacao",
            options={
                "verbose_name": "Resultado da Nota da Avaliação",
                "verbose_name_plural": "Notas das Avaliações",
            },
        ),
        migrations.AlterModelTable(
            name="resultadoavaliacao",
            table="f_resultado_avaliacao",
        ),
    ]
