services:
  - type: web
    name: avaliacao-incidentes-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
    autoDeploy: false