# Generated by Django 4.2.10 on 2025-02-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "sys_id",
                    models.CharField(
                        help_text="ID único do incidente no ServiceNow",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número do incidente", max_length=255, null=True
                    ),
                ),
                (
                    "sys_created_on",
                    models.DateTimeField(
                        help_text="Data e hora de criação do registro", null=True
                    ),
                ),
                (
                    "sys_updated_on",
                    models.DateTimeField(
                        help_text="Data e hora da última atualização", null=True
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        help_text="Data e hora de abertura do incidente", null=True
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        help_text="Data e hora de fechamento do incidente", null=True
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        help_text="Data e hora de resolução do incidente", null=True
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        help_text="Status numérico do incidente", null=True
                    ),
                ),
                (
                    "dv_state",
                    models.CharField(
                        help_text="Descrição do status do incidente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Nível de prioridade numérico", null=True
                    ),
                ),
                (
                    "dv_priority",
                    models.CharField(
                        help_text="Descrição do nível de prioridade",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "impact",
                    models.IntegerField(
                        help_text="Nível de impacto numérico", null=True
                    ),
                ),
                (
                    "dv_impact",
                    models.CharField(
                        help_text="Descrição do nível de impacto",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "urgency",
                    models.IntegerField(
                        help_text="Nível de urgência numérico", null=True
                    ),
                ),
                (
                    "dv_urgency",
                    models.CharField(
                        help_text="Descrição do nível de urgência",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "incident_state",
                    models.IntegerField(
                        help_text="Estado do incidente numérico", null=True
                    ),
                ),
                (
                    "dv_incident_state",
                    models.CharField(
                        help_text="Descrição do estado do incidente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Descrição curta do incidente", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição completa do incidente", null=True
                    ),
                ),
                (
                    "close_notes",
                    models.TextField(
                        help_text="Notas de fechamento do incidente", null=True
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        help_text="ID do usuário designado", max_length=255, null=True
                    ),
                ),
                (
                    "dv_assigned_to",
                    models.CharField(
                        help_text="Nome do usuário designado", max_length=255, null=True
                    ),
                ),
                (
                    "assignment_group",
                    models.CharField(
                        help_text="ID do grupo designado", max_length=255, null=True
                    ),
                ),
                (
                    "dv_assignment_group",
                    models.CharField(
                        help_text="Nome do grupo designado", max_length=255, null=True
                    ),
                ),
                (
                    "u_tipo_incidente",
                    models.CharField(
                        help_text="Tipo de incidente", max_length=255, null=True
                    ),
                ),
                (
                    "u_tempo_indisponivel",
                    models.DateTimeField(
                        help_text="Tempo total de indisponibilidade", null=True
                    ),
                ),
                (
                    "business_duration",
                    models.DateTimeField(
                        help_text="Duração em horário comercial", null=True
                    ),
                ),
                (
                    "dv_business_duration",
                    models.CharField(
                        help_text="Descrição da duração em horário comercial",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "business_impact",
                    models.CharField(
                        help_text="Impacto comercial", max_length=255, null=True
                    ),
                ),
                (
                    "business_service",
                    models.CharField(
                        help_text="Serviço comercial", max_length=255, null=True
                    ),
                ),
                (
                    "dv_business_service",
                    models.CharField(
                        help_text="Descrição do serviço comercial",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "business_stc",
                    models.IntegerField(help_text="STC comercial", null=True),
                ),
                (
                    "calendar_duration",
                    models.DateTimeField(help_text="Duração do calendário", null=True),
                ),
                (
                    "dv_calendar_duration",
                    models.CharField(
                        help_text="Descrição da duração do calendário",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "calendar_stc",
                    models.IntegerField(help_text="STC do calendário", null=True),
                ),
                (
                    "caller_id",
                    models.CharField(
                        help_text="ID do chamador", max_length=255, null=True
                    ),
                ),
                (
                    "dv_caller_id",
                    models.CharField(
                        help_text="Descrição do chamador", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(help_text="Categoria", max_length=255, null=True),
                ),
                (
                    "dv_category",
                    models.CharField(
                        help_text="Descrição da categoria", max_length=255, null=True
                    ),
                ),
                (
                    "cause",
                    models.CharField(help_text="Causa", max_length=255, null=True),
                ),
                (
                    "caused_by",
                    models.CharField(
                        help_text="Causado por", max_length=255, null=True
                    ),
                ),
                (
                    "dv_caused_by",
                    models.CharField(
                        help_text="Descrição do causador", max_length=255, null=True
                    ),
                ),
                (
                    "child_incidents",
                    models.IntegerField(help_text="Incidentes filhos", null=True),
                ),
                (
                    "close_code",
                    models.CharField(
                        help_text="Código de fechamento", max_length=255, null=True
                    ),
                ),
                (
                    "dv_close_code",
                    models.CharField(
                        help_text="Descrição do código de fechamento",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "closed_by",
                    models.CharField(
                        help_text="Fechado por", max_length=255, null=True
                    ),
                ),
                (
                    "dv_closed_by",
                    models.CharField(
                        help_text="Descrição de quem fechou", max_length=255, null=True
                    ),
                ),
                (
                    "cmdb_ci",
                    models.CharField(help_text="CI do CMDB", max_length=255, null=True),
                ),
                (
                    "dv_cmdb_ci",
                    models.CharField(
                        help_text="Descrição do CI do CMDB", max_length=255, null=True
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        help_text="Comentários", max_length=255, null=True
                    ),
                ),
                (
                    "comments_and_work_notes",
                    models.CharField(
                        help_text="Comentários e notas de trabalho",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        help_text="Tipo de contato", max_length=255, null=True
                    ),
                ),
                (
                    "dv_contact_type",
                    models.CharField(
                        help_text="Descrição do tipo de contato",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "correlation_display",
                    models.CharField(
                        help_text="Exibição de correlação", max_length=255, null=True
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        help_text="ID de correlação", max_length=255, null=True
                    ),
                ),
                (
                    "delivery_plan",
                    models.CharField(
                        help_text="Plano de entrega", max_length=255, null=True
                    ),
                ),
                (
                    "dv_delivery_plan",
                    models.CharField(
                        help_text="Descrição do plano de entrega",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "delivery_task",
                    models.CharField(
                        help_text="Tarefa de entrega", max_length=255, null=True
                    ),
                ),
                (
                    "dv_delivery_task",
                    models.CharField(
                        help_text="Descrição da tarefa de entrega",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(help_text="Data de vencimento", null=True),
                ),
                ("escalation", models.IntegerField(help_text="Escalação", null=True)),
                (
                    "dv_escalation",
                    models.CharField(
                        help_text="Descrição da escalação", max_length=255, null=True
                    ),
                ),
                (
                    "expected_start",
                    models.DateTimeField(help_text="Início esperado", null=True),
                ),
                (
                    "follow_up",
                    models.DateTimeField(help_text="Acompanhamento", null=True),
                ),
                (
                    "group_list",
                    models.CharField(
                        help_text="Lista de grupos", max_length=255, null=True
                    ),
                ),
                (
                    "hold_reason",
                    models.IntegerField(help_text="Motivo de espera", null=True),
                ),
                (
                    "dv_hold_reason",
                    models.CharField(
                        help_text="Descrição do motivo de espera",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("knowledge", models.BooleanField(help_text="Conhecimento", null=True)),
                (
                    "lessons_learned",
                    models.TextField(help_text="Lições aprendidas", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Localização", max_length=255, null=True
                    ),
                ),
                (
                    "dv_location",
                    models.CharField(
                        help_text="Descrição da localização", max_length=255, null=True
                    ),
                ),
                ("made_sla", models.BooleanField(help_text="SLA cumprido", null=True)),
                (
                    "major_incident_state",
                    models.CharField(
                        help_text="Estado de incidente maior", max_length=255, null=True
                    ),
                ),
                (
                    "dv_major_incident_state",
                    models.CharField(
                        help_text="Descrição do estado de incidente maior",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "needs_attention",
                    models.BooleanField(help_text="Precisa de atenção", null=True),
                ),
                ("notify", models.IntegerField(help_text="Notificar", null=True)),
                (
                    "dv_notify",
                    models.CharField(
                        help_text="Descrição da notificação", max_length=255, null=True
                    ),
                ),
                (
                    "origin_id",
                    models.CharField(
                        help_text="ID de origem", max_length=255, null=True
                    ),
                ),
                (
                    "origin_table",
                    models.CharField(
                        help_text="Tabela de origem", max_length=255, null=True
                    ),
                ),
                ("overview", models.TextField(help_text="Visão geral", null=True)),
                (
                    "parent",
                    models.CharField(help_text="Pai", max_length=255, null=True),
                ),
                (
                    "dv_parent",
                    models.CharField(
                        help_text="Descrição do pai", max_length=255, null=True
                    ),
                ),
                (
                    "parent_incident",
                    models.CharField(
                        help_text="Incidente pai", max_length=255, null=True
                    ),
                ),
                (
                    "dv_parent_incident",
                    models.CharField(
                        help_text="Descrição do incidente pai",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "problem_id",
                    models.CharField(
                        help_text="ID do problema", max_length=255, null=True
                    ),
                ),
                (
                    "dv_problem_id",
                    models.CharField(
                        help_text="Descrição do ID do problema",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "promoted_by",
                    models.CharField(
                        help_text="Promovido por", max_length=255, null=True
                    ),
                ),
                (
                    "dv_promoted_by",
                    models.CharField(
                        help_text="Descrição de quem promoveu",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "promoted_on",
                    models.DateTimeField(help_text="Promovido em", null=True),
                ),
                (
                    "proposed_by",
                    models.CharField(
                        help_text="Proposto por", max_length=255, null=True
                    ),
                ),
                (
                    "dv_proposed_by",
                    models.CharField(
                        help_text="Descrição de quem propôs", max_length=255, null=True
                    ),
                ),
                (
                    "proposed_on",
                    models.DateTimeField(help_text="Proposto em", null=True),
                ),
                (
                    "reassignment_count",
                    models.IntegerField(
                        help_text="Contagem de reatribuições", null=True
                    ),
                ),
                (
                    "reopen_count",
                    models.IntegerField(help_text="Contagem de reaberturas", null=True),
                ),
                (
                    "reopened_by",
                    models.CharField(
                        help_text="Reaberto por", max_length=255, null=True
                    ),
                ),
                (
                    "dv_reopened_by",
                    models.CharField(
                        help_text="Descrição de quem reabriu", max_length=255, null=True
                    ),
                ),
                (
                    "reopened_time",
                    models.DateTimeField(help_text="Hora de reabertura", null=True),
                ),
                ("rfc", models.CharField(help_text="RFC", max_length=255, null=True)),
                (
                    "dv_rfc",
                    models.CharField(
                        help_text="Descrição do RFC", max_length=255, null=True
                    ),
                ),
                (
                    "route_reason",
                    models.IntegerField(help_text="Motivo da rota", null=True),
                ),
                (
                    "dv_route_reason",
                    models.CharField(
                        help_text="Descrição do motivo da rota",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scr_vendor",
                    models.CharField(
                        help_text="Fornecedor SCR", max_length=255, null=True
                    ),
                ),
                (
                    "dv_scr_vendor",
                    models.CharField(
                        help_text="Descrição do fornecedor SCR",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scr_vendor_closed_at",
                    models.DateTimeField(
                        help_text="Fechado pelo fornecedor SCR em", null=True
                    ),
                ),
                (
                    "scr_vendor_opened_at",
                    models.DateTimeField(
                        help_text="Aberto pelo fornecedor SCR em", null=True
                    ),
                ),
                (
                    "scr_vendor_point_of_contact",
                    models.CharField(
                        help_text="Ponto de contato do fornecedor SCR",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scr_vendor_resolved_at",
                    models.DateTimeField(
                        help_text="Resolvido pelo fornecedor SCR em", null=True
                    ),
                ),
                (
                    "scr_vendor_ticket",
                    models.CharField(
                        help_text="Ticket do fornecedor SCR", max_length=255, null=True
                    ),
                ),
                (
                    "service_offering",
                    models.CharField(
                        help_text="Oferta de serviço", max_length=255, null=True
                    ),
                ),
                (
                    "dv_service_offering",
                    models.CharField(
                        help_text="Descrição da oferta de serviço",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("severity", models.IntegerField(help_text="Severidade", null=True)),
                (
                    "dv_severity",
                    models.CharField(
                        help_text="Descrição da severidade", max_length=255, null=True
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        help_text="Habilidades", max_length=255, null=True
                    ),
                ),
                (
                    "sla_due",
                    models.DateTimeField(help_text="Vencimento do SLA", null=True),
                ),
                (
                    "sn_ind_tsm_core_incident",
                    models.BooleanField(help_text="Incidente principal TSM", null=True),
                ),
                (
                    "sn_ind_tsm_core_stage",
                    models.CharField(
                        help_text="Estágio principal TSM", max_length=255, null=True
                    ),
                ),
                (
                    "dv_sn_ind_tsm_core_stage",
                    models.CharField(
                        help_text="Descrição do estágio principal TSM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        help_text="Subcategoria", max_length=255, null=True
                    ),
                ),
                (
                    "dv_subcategory",
                    models.CharField(
                        help_text="Descrição da subcategoria", max_length=255, null=True
                    ),
                ),
                (
                    "sys_class_name",
                    models.CharField(
                        help_text="Nome da classe do sistema", max_length=255, null=True
                    ),
                ),
                (
                    "dv_sys_class_name",
                    models.CharField(
                        help_text="Descrição do nome da classe do sistema",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sys_domain",
                    models.CharField(
                        help_text="Domínio do sistema", max_length=255, null=True
                    ),
                ),
                (
                    "sys_domain_path",
                    models.CharField(
                        help_text="Caminho do domínio do sistema",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "task_effective_number",
                    models.CharField(
                        help_text="Número efetivo da tarefa", max_length=255, null=True
                    ),
                ),
                (
                    "time_worked",
                    models.DateTimeField(help_text="Tempo trabalhado", null=True),
                ),
                (
                    "dv_time_worked",
                    models.CharField(
                        help_text="Descrição do tempo trabalhado",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("timeline", models.TextField(help_text="Linha do tempo", null=True)),
                (
                    "trigger_rule",
                    models.CharField(
                        help_text="Regra de gatilho", max_length=255, null=True
                    ),
                ),
                (
                    "dv_trigger_rule",
                    models.CharField(
                        help_text="Descrição da regra de gatilho",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_alert_ingest",
                    models.DateTimeField(help_text="Ingestão de alerta", null=True),
                ),
                (
                    "u_alert_name",
                    models.TextField(help_text="Nome do alerta", null=True),
                ),
                (
                    "u_anexo",
                    models.CharField(help_text="Anexo", max_length=255, null=True),
                ),
                (
                    "u_b2b_downtime",
                    models.DateTimeField(
                        help_text="Tempo de inatividade B2B", null=True
                    ),
                ),
                (
                    "dv_u_b2b_downtime",
                    models.CharField(
                        help_text="Descrição do tempo de inatividade B2B",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_b2b_purge_report",
                    models.BooleanField(help_text="Relatório de purga B2B", null=True),
                ),
                (
                    "u_bloquear_ticket",
                    models.CharField(
                        help_text="Bloquear ticket", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_bloquear_ticket",
                    models.CharField(
                        help_text="Descrição do bloqueio de ticket",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_c_digo_da_falha",
                    models.CharField(
                        help_text="Código da falha", max_length=255, null=True
                    ),
                ),
                (
                    "u_case_ticket_vivo",
                    models.CharField(
                        help_text="Ticket Vivo do caso", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_case_ticket_vivo",
                    models.CharField(
                        help_text="Descrição do ticket Vivo do caso",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_case_vivo_ticket_number",
                    models.CharField(
                        help_text="Número do ticket Vivo do caso",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_categoria_da_falha",
                    models.CharField(
                        help_text="Categoria da falha", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_categoria_da_falha",
                    models.CharField(
                        help_text="Descrição da categoria da falha",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_categorizacao_n1",
                    models.CharField(
                        help_text="Categorização N1", max_length=255, null=True
                    ),
                ),
                (
                    "u_categorizacao_n2",
                    models.CharField(
                        help_text="Categorização N2", max_length=255, null=True
                    ),
                ),
                (
                    "u_categorizacao_n3",
                    models.CharField(
                        help_text="Categorização N3", max_length=255, null=True
                    ),
                ),
                ("u_cep", models.CharField(help_text="CEP", max_length=255, null=True)),
                (
                    "u_chamado_tratado_por_analista",
                    models.CharField(
                        help_text="Chamado tratado por analista",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dv_u_chamado_tratado_por_analista",
                    models.CharField(
                        help_text="Descrição do chamado tratado por analista",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_cidade",
                    models.CharField(help_text="Cidade", max_length=255, null=True),
                ),
                (
                    "u_classificacao_da_unidade",
                    models.CharField(
                        help_text="Classificação da unidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_cloud_provider",
                    models.CharField(
                        help_text="Provedor de nuvem", max_length=255, null=True
                    ),
                ),
                (
                    "u_cmdb_ci",
                    models.CharField(help_text="CI do CMDB", max_length=255, null=True),
                ),
                (
                    "dv_u_cmdb_ci",
                    models.CharField(
                        help_text="Descrição do CI do CMDB", max_length=255, null=True
                    ),
                ),
                (
                    "u_cnpj",
                    models.CharField(help_text="CNPJ", max_length=255, null=True),
                ),
                (
                    "u_comentarios_adicionais",
                    models.CharField(
                        help_text="Comentários adicionais", max_length=255, null=True
                    ),
                ),
                (
                    "u_comment_inserted",
                    models.BooleanField(help_text="Comentário inserido", null=True),
                ),
                (
                    "u_company_name",
                    models.CharField(
                        help_text="Nome da empresa", max_length=255, null=True
                    ),
                ),
                (
                    "u_complaint",
                    models.CharField(help_text="Reclamação", max_length=255, null=True),
                ),
                (
                    "u_complaint_sub",
                    models.CharField(
                        help_text="Sub-reclamação", max_length=255, null=True
                    ),
                ),
                (
                    "u_contato_autorizado_lca",
                    models.CharField(
                        help_text="Contato autorizado LCA", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_contato_autorizado_lca",
                    models.CharField(
                        help_text="Descrição do contato autorizado LCA",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_contato_email",
                    models.CharField(
                        help_text="Email do contato", max_length=255, null=True
                    ),
                ),
                (
                    "u_contato_nome",
                    models.CharField(
                        help_text="Nome do contato", max_length=255, null=True
                    ),
                ),
                (
                    "u_contato_telefone",
                    models.CharField(
                        help_text="Telefone do contato", max_length=255, null=True
                    ),
                ),
                (
                    "u_contatos_adicionais",
                    models.CharField(
                        help_text="Contatos adicionais", max_length=255, null=True
                    ),
                ),
                (
                    "u_customer_pending_time",
                    models.DateTimeField(
                        help_text="Tempo pendente do cliente", null=True
                    ),
                ),
                (
                    "dv_u_customer_pending_time",
                    models.CharField(
                        help_text="Descrição do tempo pendente do cliente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_data_demisto",
                    models.DateTimeField(help_text="Data Demisto", null=True),
                ),
                (
                    "u_data_normalizacao_servico",
                    models.DateTimeField(
                        help_text="Data de normalização do serviço", null=True
                    ),
                ),
                (
                    "u_data_prevista_para_atendimento",
                    models.CharField(
                        help_text="Data prevista para atendimento",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_descri_o_do_problema",
                    models.CharField(
                        help_text="Descrição do problema", max_length=255, null=True
                    ),
                ),
                (
                    "u_designador",
                    models.CharField(help_text="Designador", max_length=255, null=True),
                ),
                (
                    "u_designador_do_circuito",
                    models.CharField(
                        help_text="Designador do circuito", max_length=255, null=True
                    ),
                ),
                (
                    "u_detail_subcategory",
                    models.CharField(
                        help_text="Subcategoria de detalhes", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_detail_subcategory",
                    models.CharField(
                        help_text="Descrição da subcategoria de detalhes",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_detalhe_23",
                    models.CharField(help_text="Detalhe 23", max_length=255, null=True),
                ),
                (
                    "u_detalhe_solucoes",
                    models.CharField(
                        help_text="Detalhe das soluções", max_length=255, null=True
                    ),
                ),
                (
                    "u_detalhe_sub_categoria_da_falha",
                    models.CharField(
                        help_text="Detalhe da subcategoria da falha",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_detalhes_adicionais",
                    models.CharField(
                        help_text="Detalhes adicionais", max_length=255, null=True
                    ),
                ),
                ("u_duration", models.DateTimeField(help_text="Duração", null=True)),
                (
                    "dv_u_duration",
                    models.CharField(
                        help_text="Descrição da duração", max_length=255, null=True
                    ),
                ),
                (
                    "u_endereco_da_localidade",
                    models.CharField(
                        help_text="Endereço da localidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_endereco_da_unidade",
                    models.CharField(
                        help_text="Endereço da unidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_endereco_do_ponto",
                    models.CharField(
                        help_text="Endereço do ponto", max_length=255, null=True
                    ),
                ),
                (
                    "u_event_action",
                    models.CharField(
                        help_text="Ação do evento", max_length=255, null=True
                    ),
                ),
                (
                    "u_event_ingest",
                    models.DateTimeField(help_text="Ingestão do evento", null=True),
                ),
                (
                    "u_expected_resolution_time",
                    models.DateTimeField(
                        help_text="Tempo esperado de resolução", null=True
                    ),
                ),
                (
                    "dv_u_expected_resolution_time",
                    models.CharField(
                        help_text="Descrição do tempo esperado de resolução",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_expected_response_time",
                    models.DateTimeField(
                        help_text="Tempo esperado de resposta", null=True
                    ),
                ),
                (
                    "dv_u_expected_response_time",
                    models.CharField(
                        help_text="Descrição do tempo esperado de resposta",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_expected_service_time",
                    models.DateTimeField(
                        help_text="Tempo esperado de serviço", null=True
                    ),
                ),
                (
                    "dv_u_expected_service_time",
                    models.CharField(
                        help_text="Descrição do tempo esperado de serviço",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_grupo",
                    models.CharField(help_text="Grupo", max_length=255, null=True),
                ),
                (
                    "dv_u_grupo",
                    models.CharField(
                        help_text="Descrição do grupo", max_length=255, null=True
                    ),
                ),
                (
                    "u_hostname",
                    models.CharField(
                        help_text="Nome do host", max_length=255, null=True
                    ),
                ),
                (
                    "u_id_da_unidade",
                    models.CharField(
                        help_text="ID da unidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_id_demisto",
                    models.CharField(help_text="ID Demisto", max_length=255, null=True),
                ),
                (
                    "u_id_do_ponto",
                    models.CharField(
                        help_text="ID do ponto", max_length=255, null=True
                    ),
                ),
                (
                    "u_id_do_ponto_ii",
                    models.CharField(
                        help_text="ID do ponto II", max_length=255, null=True
                    ),
                ),
                (
                    "u_id_do_solicitante",
                    models.CharField(
                        help_text="ID do solicitante", max_length=255, null=True
                    ),
                ),
                (
                    "u_id_sigla_da_unidade",
                    models.CharField(
                        help_text="Sigla da unidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_id_vantive",
                    models.CharField(help_text="ID Vantive", max_length=255, null=True),
                ),
                (
                    "u_id_vgr",
                    models.CharField(help_text="ID VGR", max_length=255, null=True),
                ),
                (
                    "u_identificacao_do_hardware",
                    models.CharField(
                        help_text="Identificação do hardware", max_length=255, null=True
                    ),
                ),
                (
                    "u_identificacao_do_ponto",
                    models.CharField(
                        help_text="Identificação do ponto", max_length=255, null=True
                    ),
                ),
                (
                    "u_impact_do_ticket",
                    models.CharField(
                        help_text="Impacto do ticket", max_length=255, null=True
                    ),
                ),
                (
                    "u_inicio_sprint",
                    models.DateField(help_text="Início do sprint", null=True),
                ),
                (
                    "u_integration",
                    models.BooleanField(help_text="Integração", null=True),
                ),
                (
                    "u_ip_destination",
                    models.CharField(
                        help_text="IP de destino", max_length=255, null=True
                    ),
                ),
                (
                    "u_ip_origin",
                    models.CharField(
                        help_text="IP de origem", max_length=255, null=True
                    ),
                ),
                (
                    "u_line",
                    models.CharField(help_text="Linha", max_length=255, null=True),
                ),
                (
                    "u_link_type",
                    models.CharField(
                        help_text="Tipo de link", max_length=255, null=True
                    ),
                ),
                ("u_lp", models.CharField(help_text="LP", max_length=255, null=True)),
                (
                    "u_nome_da_unidade",
                    models.CharField(
                        help_text="Nome da unidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_nome_do_ponto",
                    models.CharField(
                        help_text="Nome do ponto", max_length=255, null=True
                    ),
                ),
                (
                    "u_nome_do_respons_vel_pela_abertura_do_chamado",
                    models.CharField(
                        help_text="Nome do responsável pela abertura do chamado",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_number_mass",
                    models.CharField(
                        help_text="Número MASS", max_length=255, null=True
                    ),
                ),
                (
                    "u_number_sigitm",
                    models.CharField(
                        help_text="Número SIGITM", max_length=255, null=True
                    ),
                ),
                (
                    "u_numero_do_contrato_dados",
                    models.CharField(
                        help_text="Número do contrato de dados",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_numero_do_contrato_voz",
                    models.CharField(
                        help_text="Número do contrato de voz", max_length=255, null=True
                    ),
                ),
                (
                    "u_observacao_da_perda_do_sla",
                    models.CharField(
                        help_text="Observação da perda do SLA",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_opened_month",
                    models.CharField(
                        help_text="Mês de abertura", max_length=255, null=True
                    ),
                ),
                (
                    "u_opening_reason",
                    models.CharField(
                        help_text="Motivo de abertura", max_length=255, null=True
                    ),
                ),
                (
                    "u_operational_system",
                    models.CharField(
                        help_text="Sistema operacional", max_length=255, null=True
                    ),
                ),
                (
                    "u_port_destination",
                    models.CharField(
                        help_text="Porta de destino", max_length=255, null=True
                    ),
                ),
                (
                    "u_port_origin",
                    models.CharField(
                        help_text="Porta de origem", max_length=255, null=True
                    ),
                ),
                (
                    "u_portal_solicitacoes",
                    models.BooleanField(help_text="Portal de solicitações", null=True),
                ),
                (
                    "u_procedencia",
                    models.CharField(
                        help_text="Procedência", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_procedencia",
                    models.CharField(
                        help_text="Descrição da procedência", max_length=255, null=True
                    ),
                ),
                (
                    "u_product_category",
                    models.CharField(
                        help_text="Categoria do produto", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_product_category",
                    models.CharField(
                        help_text="Descrição da categoria do produto",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_product_subcategory",
                    models.CharField(
                        help_text="Subcategoria do produto", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_product_subcategory",
                    models.CharField(
                        help_text="Descrição da subcategoria do produto",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_product_subcategory_detail",
                    models.CharField(
                        help_text="Detalhe da subcategoria do produto",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dv_u_product_subcategory_detail",
                    models.CharField(
                        help_text="Descrição do detalhe da subcategoria do produto",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_product_vivo",
                    models.CharField(
                        help_text="Produto Vivo", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_product_vivo",
                    models.CharField(
                        help_text="Descrição do produto Vivo", max_length=255, null=True
                    ),
                ),
                (
                    "u_produto_n1",
                    models.CharField(help_text="Produto N1", max_length=255, null=True),
                ),
                (
                    "u_produto_n2",
                    models.CharField(help_text="Produto N2", max_length=255, null=True),
                ),
                (
                    "u_produto_n3",
                    models.CharField(help_text="Produto N3", max_length=255, null=True),
                ),
                (
                    "u_rede",
                    models.CharField(help_text="Rede", max_length=255, null=True),
                ),
                (
                    "dv_u_rede",
                    models.CharField(
                        help_text="Descrição da rede", max_length=255, null=True
                    ),
                ),
                (
                    "u_reincidencia",
                    models.CharField(
                        help_text="Reincidência", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_reincidencia",
                    models.CharField(
                        help_text="Descrição da reincidência", max_length=255, null=True
                    ),
                ),
                (
                    "u_resent_remedy",
                    models.IntegerField(help_text="Remédio reenviado", null=True),
                ),
                (
                    "u_resolution_time",
                    models.DateTimeField(help_text="Tempo de resolução", null=True),
                ),
                (
                    "dv_u_resolution_time",
                    models.CharField(
                        help_text="Descrição do tempo de resolução",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_response_time",
                    models.DateTimeField(help_text="Tempo de resposta", null=True),
                ),
                (
                    "dv_u_response_time",
                    models.CharField(
                        help_text="Descrição do tempo de resposta",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_rpt_deteccao_inc_ate_ticket",
                    models.DateTimeField(
                        help_text="Detecção do incidente até o ticket", null=True
                    ),
                ),
                (
                    "dv_u_rpt_deteccao_inc_ate_ticket",
                    models.CharField(
                        help_text="Descrição da detecção do incidente até o ticket",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_rpt_tempo_de_abertura_encerramento",
                    models.DateTimeField(
                        help_text="Tempo de abertura até encerramento", null=True
                    ),
                ),
                (
                    "dv_u_rpt_tempo_de_abertura_encerramento",
                    models.CharField(
                        help_text="Descrição do tempo de abertura até encerramento",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_rpt_tempo_de_deteccao_do_inc_ate_a_abertura_do_ticket",
                    models.DateTimeField(
                        help_text="Tempo de detecção do incidente até a abertura do ticket",
                        null=True,
                    ),
                ),
                (
                    "dv_u_rpt_tempo_de_deteccao_do_inc_ate_a_abertura_do_ticket",
                    models.CharField(
                        help_text="Descrição do tempo de detecção do incidente até a abertura do ticket",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_rpt_tempo_de_processamento_da_automacao",
                    models.DateTimeField(
                        help_text="Tempo de processamento da automação", null=True
                    ),
                ),
                (
                    "dv_u_rpt_tempo_de_processamento_da_automacao",
                    models.CharField(
                        help_text="Descrição do tempo de processamento da automação",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_rpt_tempo_de_processamento_da_automacao_ate_abertura_do_ticket",
                    models.DateTimeField(
                        db_column="u_rpt_tempo_proc_autom_ticket",
                        help_text="Tempo de processamento da automação até a abertura do ticket",
                        null=True,
                    ),
                ),
                (
                    "dv_u_rpt_tempo_de_processamento_da_automacao_ate_abertura_do_ticket",
                    models.CharField(
                        db_column="dv_u_rpt_tempo_proc_autom_ticket",
                        help_text="Descrição do tempo de processamento da automação até a abertura do ticket",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_rpt_tempo_detecao_hora",
                    models.DateTimeField(
                        help_text="Tempo de detecção em horas", null=True
                    ),
                ),
                (
                    "dv_u_rpt_tempo_detecao_hora",
                    models.CharField(
                        help_text="Descrição do tempo de detecção em horas",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_serial_do_equipamento",
                    models.CharField(
                        help_text="Serial do equipamento", max_length=255, null=True
                    ),
                ),
                (
                    "u_serial_number",
                    models.CharField(
                        help_text="Número de série", max_length=255, null=True
                    ),
                ),
                (
                    "u_service_time",
                    models.DateTimeField(help_text="Tempo de serviço", null=True),
                ),
                (
                    "dv_u_service_time",
                    models.CharField(
                        help_text="Descrição do tempo de serviço",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_service_type",
                    models.CharField(
                        help_text="Tipo de serviço", max_length=255, null=True
                    ),
                ),
                (
                    "u_severidade_do_chamado",
                    models.CharField(
                        help_text="Severidade do chamado", max_length=255, null=True
                    ),
                ),
                (
                    "u_sigla_da_unidade",
                    models.CharField(
                        help_text="Sigla da unidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_signal_rule_description",
                    models.TextField(
                        help_text="Descrição da regra de sinal", null=True
                    ),
                ),
                (
                    "u_sla_tratativa",
                    models.CharField(
                        help_text="SLA de tratativa", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_sla_tratativa",
                    models.CharField(
                        help_text="Descrição do SLA de tratativa",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_source_instance",
                    models.CharField(
                        help_text="Instância de origem", max_length=255, null=True
                    ),
                ),
                (
                    "u_sub_categoria_da_falha",
                    models.CharField(
                        help_text="Subcategoria da falha", max_length=255, null=True
                    ),
                ),
                (
                    "u_suport_group_name",
                    models.CharField(
                        help_text="Nome do grupo de suporte", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_suport_group_name",
                    models.CharField(
                        help_text="Descrição do nome do grupo de suporte",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_telefone_do_responsavel",
                    models.CharField(
                        help_text="Telefone do responsável", max_length=255, null=True
                    ),
                ),
                (
                    "u_tempo_total_da_tratativa",
                    models.CharField(
                        help_text="Tempo total da tratativa", max_length=255, null=True
                    ),
                ),
                (
                    "u_ticket_infinity",
                    models.CharField(
                        help_text="Ticket Infinity", max_length=255, null=True
                    ),
                ),
                (
                    "u_ticket_infinity_number",
                    models.CharField(
                        help_text="Número do Ticket Infinity", max_length=255, null=True
                    ),
                ),
                (
                    "u_ticket_remedy_number",
                    models.CharField(
                        help_text="Número do Ticket Remedy", max_length=255, null=True
                    ),
                ),
                (
                    "u_ticket_sigtm_number",
                    models.CharField(
                        help_text="Número do Ticket SIGTM", max_length=255, null=True
                    ),
                ),
                (
                    "u_tipo_de_procedencia",
                    models.CharField(
                        help_text="Tipo de procedência", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_tipo_de_procedencia",
                    models.CharField(
                        help_text="Descrição do tipo de procedência",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_tipo_de_servico",
                    models.CharField(
                        help_text="Tipo de serviço", max_length=255, null=True
                    ),
                ),
                (
                    "u_torre_de_atendimento",
                    models.CharField(
                        help_text="Torre de atendimento", max_length=255, null=True
                    ),
                ),
                (
                    "u_type_ritm_or_incident",
                    models.CharField(
                        help_text="Tipo de RITM ou incidente", max_length=255, null=True
                    ),
                ),
                ("u_uf", models.CharField(help_text="UF", max_length=255, null=True)),
                (
                    "u_unidade_caixa",
                    models.CharField(
                        help_text="Unidade Caixa", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_unidade_caixa",
                    models.CharField(
                        help_text="Descrição da Unidade Caixa",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_user_agent",
                    models.CharField(
                        help_text="Agente do usuário", max_length=255, null=True
                    ),
                ),
                (
                    "u_vendor_ticket",
                    models.CharField(
                        help_text="Ticket do fornecedor", max_length=255, null=True
                    ),
                ),
                ("u_vita_it", models.BooleanField(help_text="VITA IT", null=True)),
                (
                    "universal_request",
                    models.CharField(
                        help_text="Solicitação universal", max_length=255, null=True
                    ),
                ),
                (
                    "dv_universal_request",
                    models.CharField(
                        help_text="Descrição da solicitação universal",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upon_approval",
                    models.CharField(
                        help_text="Após aprovação", max_length=255, null=True
                    ),
                ),
                (
                    "dv_upon_approval",
                    models.CharField(
                        help_text="Descrição após aprovação", max_length=255, null=True
                    ),
                ),
                (
                    "upon_reject",
                    models.CharField(
                        help_text="Após rejeição", max_length=255, null=True
                    ),
                ),
                (
                    "dv_upon_reject",
                    models.CharField(
                        help_text="Descrição após rejeição", max_length=255, null=True
                    ),
                ),
                (
                    "user_input",
                    models.CharField(
                        help_text="Entrada do usuário", max_length=255, null=True
                    ),
                ),
                (
                    "watch_list",
                    models.CharField(
                        help_text="Lista de observação", max_length=255, null=True
                    ),
                ),
                (
                    "work_end",
                    models.DateTimeField(help_text="Fim do trabalho", null=True),
                ),
                (
                    "work_notes",
                    models.CharField(
                        help_text="Notas de trabalho", max_length=255, null=True
                    ),
                ),
                (
                    "work_notes_list",
                    models.CharField(
                        help_text="Lista de notas de trabalho",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "work_start",
                    models.DateTimeField(help_text="Início do trabalho", null=True),
                ),
                (
                    "u_tempo_expurgo",
                    models.DateTimeField(
                        help_text="Tempo de expurgo do incidente", null=True
                    ),
                ),
                (
                    "u_fim_indisponibilidade",
                    models.DateTimeField(
                        help_text="Data e hora do fim da indisponibilidade", null=True
                    ),
                ),
                (
                    "contract",
                    models.CharField(
                        help_text="ID do contrato", max_length=255, null=True
                    ),
                ),
                (
                    "dv_contract",
                    models.CharField(
                        help_text="Nome do contrato", max_length=255, null=True
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="ID da empresa", max_length=255, null=True
                    ),
                ),
                (
                    "dv_company",
                    models.CharField(
                        help_text="Nome da empresa", max_length=255, null=True
                    ),
                ),
                (
                    "u_tipo_indisponibilidade",
                    models.CharField(
                        help_text="Tipo de indisponibilidade", max_length=255, null=True
                    ),
                ),
                (
                    "u_justificativa_isolamento",
                    models.CharField(
                        help_text="Justificativa de isolamento",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dv_u_categoria_falha",
                    models.CharField(
                        help_text="Descrição da categoria de falha",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dv_u_sub_categoria_da_falha",
                    models.CharField(
                        help_text="Descrição da subcategoria de falha",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dv_u_detalhe_sub_categoria_da_falha",
                    models.CharField(
                        help_text="Detalhe da subcategoria de falha",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "u_origem",
                    models.CharField(
                        help_text="Origem do incidente", max_length=255, null=True
                    ),
                ),
                (
                    "dv_u_origem",
                    models.CharField(
                        help_text="Descrição da origem", max_length=255, null=True
                    ),
                ),
                (
                    "action_status",
                    models.IntegerField(help_text="Status da ação", null=True),
                ),
                (
                    "dv_action_status",
                    models.CharField(
                        help_text="Descrição do status da ação",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "actions_taken",
                    models.CharField(
                        help_text="Ações tomadas", max_length=255, null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        help_text="Se o registro está ativo", null=True
                    ),
                ),
                (
                    "activity_due",
                    models.DateTimeField(
                        help_text="Data prevista para atividade", null=True
                    ),
                ),
                (
                    "additional_assignee_list",
                    models.CharField(
                        help_text="Lista de designados adicionais",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "agile_story",
                    models.CharField(
                        help_text="História ágil relacionada", max_length=255, null=True
                    ),
                ),
                (
                    "dv_agile_story",
                    models.CharField(
                        help_text="Descrição da história ágil",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "approval",
                    models.CharField(
                        help_text="Status de aprovação", max_length=255, null=True
                    ),
                ),
                (
                    "dv_approval",
                    models.CharField(
                        help_text="Descrição do status de aprovação",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "approval_history",
                    models.CharField(
                        help_text="Histórico de aprovações", max_length=255, null=True
                    ),
                ),
                (
                    "approval_set",
                    models.DateTimeField(
                        help_text="Data de definição da aprovação", null=True
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        help_text="ID do usuário que resolveu o incidente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dv_resolved_by",
                    models.CharField(
                        help_text="Nome do usuário que resolveu o incidente",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "incident",
            },
        ),
        migrations.CreateModel(
            name="IncidentSLA",
            fields=[
                (
                    "sys_id",
                    models.CharField(
                        help_text="ID único do registro SLA no ServiceNow",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        help_text="ID da tarefa relacionada", max_length=255, null=True
                    ),
                ),
                (
                    "dv_task",
                    models.CharField(
                        help_text="Descrição da tarefa relacionada",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sla",
                    models.CharField(
                        help_text="ID do acordo SLA", max_length=255, null=True
                    ),
                ),
                (
                    "dv_sla",
                    models.CharField(
                        help_text="Descrição do acordo SLA", max_length=255, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        help_text="Estágio atual do SLA", max_length=255, null=True
                    ),
                ),
                (
                    "dv_stage",
                    models.CharField(
                        help_text="Descrição do estágio do SLA",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "business_duration",
                    models.DateTimeField(
                        help_text="Duração em horário comercial", null=True
                    ),
                ),
                (
                    "dv_business_duration",
                    models.CharField(
                        help_text="Descrição da duração em horário comercial",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Data e hora de início", null=True),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="Hora de término", null=True),
                ),
                (
                    "business_percentage",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Percentual de conclusão em horário comercial",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "has_breached",
                    models.BooleanField(help_text="Se o SLA foi violado", null=True),
                ),
                (
                    "active",
                    models.BooleanField(help_text="Se o SLA está ativo", null=True),
                ),
                (
                    "sys_created_on",
                    models.DateTimeField(
                        help_text="Data e hora de criação do registro", null=True
                    ),
                ),
                (
                    "sys_updated_on",
                    models.DateTimeField(
                        help_text="Data e hora da última atualização", null=True
                    ),
                ),
                (
                    "business_pause_duration",
                    models.DateTimeField(
                        help_text="Duração da pausa em horário comercial", null=True
                    ),
                ),
                (
                    "dv_business_pause_duration",
                    models.CharField(
                        help_text="Descrição da duração da pausa comercial",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "business_time_left",
                    models.DateTimeField(
                        help_text="Tempo restante em horário comercial", null=True
                    ),
                ),
                (
                    "dv_business_time_left",
                    models.CharField(
                        help_text="Descrição do tempo restante comercial",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DateTimeField(help_text="Duração total", null=True),
                ),
                (
                    "dv_duration",
                    models.CharField(
                        help_text="Descrição da duração total",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "original_breach_time",
                    models.DateTimeField(
                        help_text="Tempo original de violação", null=True
                    ),
                ),
                (
                    "pause_duration",
                    models.DateTimeField(help_text="Duração da pausa", null=True),
                ),
                (
                    "dv_pause_duration",
                    models.CharField(
                        help_text="Descrição da duração da pausa",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pause_time",
                    models.DateTimeField(help_text="Momento da pausa", null=True),
                ),
                (
                    "planned_end_time",
                    models.DateTimeField(
                        help_text="Tempo planejado para término", null=True
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="Fuso horário", max_length=255, null=True
                    ),
                ),
                (
                    "dv_timezone",
                    models.CharField(
                        help_text="Descrição do fuso horário", max_length=255, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Percentual de conclusão",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="Horário agendado", max_length=255, null=True
                    ),
                ),
                (
                    "dv_schedule",
                    models.CharField(
                        help_text="Descrição do horário agendado",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sys_created_by",
                    models.CharField(help_text="Criado por", max_length=255, null=True),
                ),
                (
                    "sys_mod_count",
                    models.IntegerField(
                        help_text="Contagem de modificações", null=True
                    ),
                ),
                (
                    "sys_tags",
                    models.CharField(
                        help_text="Tags do sistema", max_length=255, null=True
                    ),
                ),
                (
                    "sys_updated_by",
                    models.CharField(
                        help_text="Atualizado por", max_length=255, null=True
                    ),
                ),
                (
                    "time_left",
                    models.DateTimeField(help_text="Tempo restante", null=True),
                ),
                (
                    "dv_time_left",
                    models.CharField(
                        help_text="Descrição do tempo restante",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "incident_sla",
            },
        ),
    ]
