# Generated by Django 4.2.10 on 2025-04-14 14:07

import access.models.empresa
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[access.models.empresa.validar_cnpj],
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("telefone", models.CharField(max_length=15)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresas_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresa",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="access.empresa",
            ),
        ),
    ]
