# Generated by Django 4.2.10 on 2025-09-03 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dw_analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Premissas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qtd_incidents",
                    models.IntegerField(
                        help_text="Quantidade de incidentes a serem sorteados"
                    ),
                ),
                (
                    "meta_mensal",
                    models.IntegerField(
                        default=70, help_text="Meta mensal dos analistas em pontos"
                    ),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        help_text="Assignment Group relacionado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premissas",
                        to="dw_analytics.assignmentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premissa",
                "verbose_name_plural": "Premissas",
                "db_table": "d_premissas",
            },
        ),
        migrations.CreateModel(
            name="Criterios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("boolean", "Booleano"), ("conversao", "Conversão")],
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("peso", models.IntegerField()),
                (
                    "field_service_now",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolved_by", "Resolvido Por"),
                            ("assignment_group", "Grupo de Atendimento"),
                            ("opened_at", "Data de Abertura"),
                            ("closed_at", "Data de Fechamento"),
                            ("contract", "Contrato"),
                            ("sla_atendimento", "SLA Atendimento"),
                            ("sla_resolucao", "SLA Resolução"),
                            ("company", "Cliente"),
                            ("u_origem", "Torre de Atendimento"),
                            ("dv_u_categoria_da_falha", "Categoria da Falha"),
                            ("dv_u_sub_categoria_da_falha", "Sub Categoria da Falha"),
                            (
                                "dv_u_detalhe_sub_categoria_da_falha",
                                "Detalhe Sub Categoria",
                            ),
                        ],
                        help_text="Campo correspondente no ServiceNow",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "premissa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="premissas.premissas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério",
                "verbose_name_plural": "Critérios",
                "db_table": "d_criterios",
            },
        ),
        migrations.CreateModel(
            name="Conversao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversoes",
                        to="premissas.criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversão",
                "verbose_name_plural": "Conversões",
                "db_table": "d_conversao",
            },
        ),
    ]
