# Generated by Django 4.2.10 on 2025-03-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("premissas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premissas",
            name="is_atualizaca_logs_correto",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_category_correto",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_cliente_notificado",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_contrato_lancado",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_descricao_troubleshooting",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_has_met_first_response_target",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_horas_lancadas",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_resolution_target",
        ),
        migrations.RemoveField(
            model_name="premissas",
            name="is_ticket_encerrado_corretamente",
        ),
        migrations.CreateModel(
            name="Criterios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("boolean", "Booleano"), ("integer", "Inteiro")],
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("peso", models.IntegerField()),
                (
                    "premissa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="premissas.premissas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério",
                "verbose_name_plural": "Critérios",
                "db_table": "d_criterios",
            },
        ),
    ]
