# Generated by Django 4.2.10 on 2025-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("premissas", "0002_remove_premissas_is_atualizaca_logs_correto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterios",
            name="field_service_now",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resolved_by", "Resolvido Por"),
                    ("assignment_group", "Grupo de Atendimento"),
                    ("opened_at", "Data de Abertura"),
                    ("closed_at", "Data de Fechamento"),
                    ("contract", "Contrato"),
                    ("sla_atendimento", "SLA Atendimento"),
                    ("sla_resolucao", "SLA Resolução"),
                    ("company", "Cliente"),
                    ("u_origem", "Torre de Atendimento"),
                    ("dv_u_categoria_da_falha", "Categoria da Falha"),
                    ("dv_u_sub_categoria_da_falha", "Sub Categoria da Falha"),
                    ("dv_u_detalhe_sub_categoria_da_falha", "Detalhe Sub Categoria"),
                ],
                help_text="Campo correspondente no ServiceNow",
                max_length=100,
                null=True,
            ),
        ),
    ]
