# Generated by Django 4.2.10 on 2025-03-10 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("premissas", "0003_criterios_field_service_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterios",
            name="tipo",
            field=models.CharField(
                choices=[("boolean", "Booleano"), ("conversao", "Conversão")],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Conversao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversoes",
                        to="premissas.criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversão",
                "verbose_name_plural": "Conversões",
                "db_table": "d_conversao",
            },
        ),
    ]
