# Generated by Django 4.2.10 on 2025-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("premissas", "0004_alter_criterios_tipo_conversao"),
    ]

    operations = [
        migrations.AddField(
            model_name="premissas",
            name="meta_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=70.0,
                help_text="Meta mensal dos analistas em porcentagem",
                max_digits=5,
            ),
        ),
    ]
