# Generated by Django 4.2.10 on 2025-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("premissas", "0005_premissas_meta_mensal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premissas",
            name="meta_mensal",
            field=models.IntegerField(
                default=70, help_text="Meta mensal dos analistas em pontos"
            ),
        ),
    ]
