# Generated by Django 4.2.10 on 2025-04-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_empresa_user_empresa"),
        ("dw_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentgroup",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="access.empresa",
            ),
        ),
    ]
